apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: demo-app
    repoURL: https://github.com/koorikla/demo1 
    targetRevision: HEAD # Branch
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true