apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzy-kafka-operator
  namespace: argocd
spec:
  destination:
    namespace: strimzy-kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm-charts/helm3/strimzi-kafka-operator/
    repoURL: https://github.com/strimzi/strimzi-kafka-operator.git 
    targetRevision: 0.33.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true